# Generated by Django 5.2.8 on 2025-11-22 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_imagemproduto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text='Identificador único para URL (ex: pijamas)', unique=True)),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição no menu')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='imagemproduto',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='variacaoproduto',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_antigo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Antigo (Riscado)'),
        ),
        migrations.AddField(
            model_name='variacaoproduto',
            name='cor',
            field=models.CharField(default='Única', max_length=50),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_base',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Atual'),
        ),
        migrations.AlterUniqueTogether(
            name='variacaoproduto',
            unique_together={('produto', 'tamanho', 'cor')},
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='catalogo.categoria'),
        ),
    ]
