# Generated by Django 5.2.8 on 2025-11-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_categoria_alter_imagemproduto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variacaoproduto',
            name='codigo_hex',
            field=models.CharField(default='#ffffff', help_text='Cor em Hex (ex: #000000 para preto)', max_length=7),
        ),
    ]
